# -*- coding: utf-8 -*-
"""Exploratory Data Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14D_yDAyVd7If-VleXtK4sIHAvtrKA6XG

## Sales Report Summary
From the following dataset: *https://storage.googleapis.com/dqlab-dataset/order.csv*, determine:
- Median price paid by customers from each payment method.
- Determine the payment method that has the largest basket size (average median price).
- Change freight_value to shipping_cost and find the most expensive shipping_cost from the sales data using sort.
- For each product_category_name, what is the average weight of the product, and which is the smallest standard deviation of that weight.
- Create a sales quantity histogram from the dataset to see the distribution of sales quantity with bins = 5 and figsize = (4.5).
"""

import pandas as pd
import matplotlib.pyplot as plt
order_df = pd.read_csv("https://storage.googleapis.com/dqlab-dataset/order.csv")

median_price = order_df["price"].groupby(order_df["payment_type"]).median()
print(median_price)

order_df.rename(columns={"freight_value": "shipping_cost"}, inplace=True)
sort_value = order_df.sort_values(by="shipping_cost", ascending=0)
print(sort_value)

mean_value = order_df["product_weight_gram"].groupby(order_df["product_category_name"]).mean()
print(mean_value.sort_values())
std_value = order_df["product_weight_gram"].groupby(order_df["product_category_name"]).std()
print(std_value.sort_values())

order_df[["quantity"]].hist(figsize=(4, 5), bins=5)
plt.show()