# -*- coding: utf-8 -*-
"""Car Operating Expenses.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19mLUMDU1RhQiJZy9KcEvm2wxHoNkUrXg

# **TASK QUESTIONS**:
* How to check vehicles with odd or even plate numbers?
* How to find out total expenses for vehicles with odd and even plate numbers in 1 month?

---

# **DATA**
"""

uang_jalan = 1500000
jumlah_hari = 31
list_plat_nomor = [8993, 2198, 2501, 2735, 3772, 4837, 9152]

"""## 1. Checking vehicles with odd or even plate numbers



"""

kendaraan_genap = 0
kendaraan_ganjil = 0
for plat_nomor in list_plat_nomor:
    if plat_nomor % 2 == 0:
        kendaraan_genap += 1
    else:
        kendaraan_ganjil += 1
print(kendaraan_genap)
print(kendaraan_ganjil)

"""## 2. Find out total expenses for vehicles with odd and even plate numbers in 1 month"""

i = 1
total_pengeluaran = 0
while i <= jumlah_hari:
    if i % 2 == 0:
        total_pengeluaran += (kendaraan_genap * uang_jalan)
    else:
        total_pengeluaran += (kendaraan_ganjil * uang_jalan)
    i += 1
print(total_pengeluaran)